config/routes.rb
Rails.application.routes.draw do

  resources (:users) do
    resources(:connections)
  end

  # For details on the DSL available within this file, see https://guides.rubyonrails.org/routing.html

  get '/signup', to: "users#new", as: "signup"
  post '/signup', to: "users#create"
  get '/login', to: "sessions#new", as: "login"
  post '/login', to: "sessions#create"
  post '/logout', to: "sessions#destroy"
  get "/auth/facebook/callback", to: "sessions#create_with_fb"

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/connection.rb
class Connection < ApplicationRecord

    belongs_to :match_you, class_name: "User"
    belongs_to :you_match, class_name: "User"

end

app/models/user.rb
class User < ApplicationRecord
    
    # has_many :match_you, foreign_key: :match_you_id , class_name: "Connection"
    # has_many :you_match, through: :match_you

    # has_many :you_match, foreign_key: :you_match_id, class_name: "Connection"
    # has_many :match_you, through: :you_match

    has_many :match_you, foreign_key: :match_you_id , class_name: "Connection"
    has_many :you_match, foreign_key: :you_match_id, class_name: "Connection"
    
    has_many :matched_you, through: :match_you, source: :match_you
    has_many :you_matched, through: :you_match, source: :you_match

    has_secure_password
    validates_uniqueness_of :username
    validates_presence_of :username

    scope :younger_than_30, -> { where ("(age) <= 30")}
    scope(:older_than_30, ->(age = 30) { self.where("age > ?", age) })

    def find_my_matches     
        @user = self
        my_spirituality_matches = User.where(spirituality: "#{@user.spirituality}").ids    
        if my_spirituality_matches.include?(@user.id)
            my_spirituality_matches.delete(@user.id)
        end
        int_match = my_spirituality_matches.shift

        @connection = Connection.create(you_match_id: 777, match_you_id: 7 )
        match = @user.you_match << @connection

        binding.pry
















        self.you_match << my_spirituality_matches
        @connection2 = self.Connection.create(you_match_id: int_match, match_you_id: 999)
        Connection.create(you_match_id: 7, match_you_id: 9)
        #@connection = Connection.new
        #@user.connections.create(you_match_id: my_spirituality_matches)
        #@connection = @user.connections.create
        #self.connections.create
        #@user.match_you.build(message: 'my_spirituality_matches')        
        my_connection = Connection.create()
        @connection = self.connection.build(:you_match_id)
        self.you_match << my_spirituality_matches

    end





end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base

    helper_method(:current_user)

    def current_user
      @current_user = User.find_by(id: session[:user_id])
    end
end

app/controllers/connections_controller.rb
class ConnectionsController < ApplicationController

    
    
    
    
    
    def index
        #@user = User.find_by(id: params[:id])
        #@my_matches = @user.find_my_matches
        
        @user = User.last
        @user.find_my_matches

        @over_30 = User.older_than_30
    end

    def create
        @connection = current_user.connections.build(:connection_id => params[:connection_id])
        if @connection.save
            flash[:notice] = "successfully created connection"
            redirect_to root_url
        else
            flash[:error] = "unable to add connection"
            render :action => 'new'
        end
    end

    def destroy
        @connection = current_user.connections.find(params[:id])
        @connection.destroy
        flash[:notice] = "successfully destroyed connection"
        redirect_to root_url
    end


end

app/controllers/sessions_controller.rb
class SessionsController < ApplicationController

    def new
    end
  
    def create
      @user = User.find_by(username: params[:user][:username])
      if @user && @user.authenticate(params[:user][:password])
        session[:user_id] = @user.id
        redirect_to user_path(@user)
      elsif @user
        @errors = ["Invalid Password"]
        render :new
      else
        @errors = ["Invalid Username"]
        render :new
      end
    end
  
  
    def create_with_fb
      user = User.find_or_create_by(username: fb_auth['info']['email']) do |u|
        u.password = 'password'
      end
      if user.save
        session[:user_id] = user.id
        redirect_to user_path(user)
      else
        redirect_to signup_path
      end
    end
  
    def destroy
      session.clear
      redirect_to '/signup'
    end
  
    private
  
    def fb_auth
       self.request.env['omniauth.auth']
    end

  end

app/controllers/users_controller.rb
class UsersController < ApplicationController

    before_action(:set_user)

    def new
        @user = User.new
    end

    def create
        @user = User.new(user_params)      
        if @user.save
        session[:user_id] = @user.id
            redirect_to user_path(@user)
        else
            @errors = @user.errors.full_messages
            render :new
        end
    end

    def show
        @user = User.find_by(id: params[:id])
    end

    def edit
        set_user
    end

    def update
        if @user.update(profile_params)
            redirect_to user_path(@user)
        else
            @errors = @user.errors.full_messages
            render :edit
        end
    end

    def destroy
        @user.delete
        redirect_to "/signup"
    end

    
    private
    def user_params
        params.require(:user).permit(:username, :password, :password_confirmation)
    end

    def profile_params
        params.require(:user).permit(
            :name, :age, :gender, :race, :orientation, :past_relationship_status,
            :location, :profession, :hobbies, :spirituality,
            :match_age, :match_gender, :match_race, :match_past_relationship_status, :match_spirituality
        )
    end

    def set_user
        @user = User.find_by(id: params[:id])
    end

end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/connections_helper.rb
module ConnectionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/connections/index.html.erb
<h1> INDEX </h1>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>Matchy</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/css/bootstrap.min.css" rel="stylesheet" integrity="sha384-eOJMYsd53ii+scO/bJGFsiCZc+5NDVN2yr8+0RDqr0Ql0h+rP48ckxlpbzKgwra6" crossorigin="anonymous">
    <script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.0-beta3/dist/js/bootstrap.bundle.min.js" integrity="sha384-JEW9xMcG8R+pH31jmWH6WWP0WintQrMb4s7ZOdauHnUtxwoG2vI5DkLtS3qm9Ekf" crossorigin="anonymous"></script>



    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  
  
    </head>
    <body>

    <nav class="navbar navbar-expand-lg navbar-light" style="background-color: #e30b5c;">
      <div class="container-fluid">
        <a class="navbar-brand" href="#"> ♥ Matchy //////////////</a>
        
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarNavAltMarkup" aria-controls="navbarNavAltMarkup" aria-expanded="false" aria-label="Toggle navigation">
          <span class="navbar-toggler-icon"></span>
        </button>
        
        <div class="collapse navbar-collapse" id="navbarNavAltMarkup">
          <div class="navbar-nav">
            <%if current_user %>
              <%= button_to "Log Out", logout_path, method: :post %>
            <%else%>
              <%= button_to "Log In", login_path %>
              <%= button_to "Sign Up", signup_path %>
            <%end%>
          </div>
        </div>
      </div>
    </nav>
    
    <%= yield %>
    </body>
</html>

app/views/users/_form.html.erb
<div class="container">
<%=form_for(@user) do |f|%>
    
    <h3> About Me: </h3>
    <%=f.label("Name: ") %>
    <%=f.text_field(:name) %><br>
    
    <%=f.label("Age: ") %>
    <%=f.text_field(:age) %><br>
    
    
    <%=f.label("Gender: ") %>
    <%=f.select :gender, [['select'],['Male'], ['Female']] %><br>

    <%=f.label("Orientation: ") %>
    <%=f.select :orientation, [['select'],['seeking a woman'], ['seeking a man']] %><br>
    
    
    <%=f.label("Race: ") %>
    <%=f.select :race, [['select'], ['White'], ['Black'], ['Hispanic'], ['Asian'],  ['African'], ['Arab'], ['Mixed'], ['Other']] %><br>

    <%=f.label("Past Relationship Status: ") %>
    <%=f.select :past_relationship_status, [['select'], ['never been married'], ['divorced'], ['widower/widow']] %><br>


    <br>
    <%=f.label("Location: ") %>
    <%=f.text_field(:location) %><br>

    <%=f.label("Profession: ") %>
    <%=f.text_field(:profession) %><br>

    <%=f.label("Hobbies: ") %>
    <%=f.text_field(:hobbies) %><br>

    <%=f.label("Spirituality: ") %>
    <%=f.select :spirituality, [['select'],['Non-Religious'], ['Christian'], ['Muslim'], ['Hindu'], ['Buddhist'], ['Other']] %><br>
    
    <br>
    <h3> Looking for a Match with: </h3>
    <%=f.label("My Match's Gender: ") %>
    <%=f.select :match_gender, [['select'],['Male'], ['Female']] %><br>


    <%=f.label("My Match's Age: ") %>
    <%=f.select :match_age, [['select'],['21-25'], ['26-30'], ['31-35'], ['36-40'], ['40-45'], ['46-50'], ['51-60']] %><br>

    <%=f.label("My Match's Race: ") %>
    <%=f.select :match_race, [['select'], ['White'], ['Black'], ['Hispanic'], ['Asian'], ['African'], ['Arab'], ['Mixed'], ['Other']] %><br>

    
    <%=f.label("My Match's Past Relationship Status: ") %>
    <%=f.select :match_past_relationship_status, [['select'], ['never been married'], ['divorced'], ['widower/widow']] %><br>

    <%=f.label("My Match's Spirituality: ") %>
    <%=f.select :match_spirituality, [['select'],['Non-Religious'], ['Christian'], ['Muslim'], ['Hindu'], ['Buddhist'], ['Other']] %><br>
   
    
    <br>
    <br> <%=f.submit "Submit"%>
<%end%>
</div>

app/views/users/_profile.html.erb
<div class="container">
    <h2><%= @user.name %></h2>
    <h5>Age: <%= @user.age %></h5>
    <h5>Gender: <%= @user.gender %></h5>
    <h5>Race: <%= @user.race %></h5>
    <h5>Orientation: <%= @user.orientation %></h5>
    <h5>Past Relationships: <%= @user.past_relationship_status %></h5>
    <h5>Location: <%= @user.location %></h5>
    <h5>Profession: <%= @user.profession %></h5>
    <h5>Hobbies: <%= @user.hobbies %></h5>
    <h5>Spirituality: <%= @user.spirituality %></h5>

    <br>
    <h2> Seeking Match with: </h2>
    <h5> Age: <%= @user.match_age %></h5>
    <h5> Gender: <%= @user.match_gender %></h5>
    <h5> Race: <%= @user.match_race %></h5>
    <h5> Past Relationships: <%= @user.match_past_relationship_status %></h5>
    <h5> Spirituality: <%= @user.match_spirituality %></h5>

    <br>
    <%=link_to "Edit My Profile", edit_user_path(@user), class: 'btn btn-dark btn-sm'%>
    <br>
    <br>
    <%=link_to "// Find My Matches! //", user_connections_path(@user), class: 'btn btn-warning btn-lg'%>
    <br>
</div>

app/views/users/edit.html.erb
<% @errors && @errors.each do |e| %>
    <li><%=e%></li>
  <%end%>

<%=render('form')%>

app/views/users/new.html.erb
<div class="text-center">
  <form style="max-width:500px;margin:auto;">

  <br>
  <h2>Sign Up</h2>

    <% @errors && @errors.each do |e| %>
      <li><%=e%></li>
    <%end%>
   

    <%= form_for @user, url: signup_path do |f| %>
    
      <%=f.label "Username"%>
      <div class="mb-3">
      <%=f.text_field :username %><br>
      </div>

      <%=f.label "Password"%>
      <div class="mb-1">
      <%=f.password_field :password %><br>
      </div>

      <%=f.label "Password Confirmation"%>
      <div class="mb-1">
      <%=f.password_field :password_confirmation %><br>
      </div>

      <%=f.submit "Sign Up"%>

    <%end%>

    <br>
    

    <%=link_to "Sign Up With Facebook", '/auth/facebook'%>

    <%=link_to "Sign Up With Facebook", '/auth/facebook', class: 'btn btn-primary btn-sm' %>



</div>

<br>
<br>
<div class="text-center">
  <form style="max-width:250px;margin:auto;">
    <h2>Sign Up</h2>

    <% @errors && @errors.each do |e| %>
      <li><%=e%></li>
    <%end%>
  
    <%= form_for @user, url: signup_path do |f| %>    
      <div class="field form-group">
      <%=f.label "Username"%>
      <%=f.text_field :username, class: 'form-control'%>
      </div>


      <div class="field form-group">
      <%=f.label "Password"%>
      <%=f.password_field :password, class: 'form-control' %>
      </div>

      <div class="field form-group">
      <%=f.label "Password Confirmation"%>
      <%=f.password_field :password_confirmation, class: 'form-control' %>
      </div>

      <br>
      <%=f.submit "Sign Up"%><br>
      <br>
      <%=link_to "Sign Up With Facebook", '/auth/facebook', class: 'btn btn-primary btn-sm' %>
    <%end%>
</div>

<br>
<br>

<%= form_for @user, url: signup_path do |f| %>
  <%=f.label "Username"%>
  <%=f.text_field :username%><br>
  <%=f.label "Password"%>
  <%=f.password_field :password %><br>
  <%=f.label "Password Confirmation"%>
  <%=f.password_field :password_confirmation %><br>
  <%=f.submit "Sign Up"%>
<%end%>

app/views/users/show.html.erb
<div class="container">
    <br>
    <h1> My Profile</h1>

    <% if @user.name == nil %>
        <%=render partial: 'form'%>
    <%else%>
        <%=render partial: 'profile'%>
    <%end%>
    <br>
</div>